spring:
  application:
    name: redis-lock
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 500
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dubbo?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
  rabbitmq:
    host: 119.23.187.31
    port: 5672
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirms: true

server:
  port: 8888
  servlet:
    context-path: /oy
  tomcat:
    max-connections: 10000

